import HamiltonianReduction
set_option autoImplicit false
set_option maxRecDepth 100000
namespace JSP846Standard
def upperEdges : List (Nat × Nat) := [(0,1),(0,20),(0,40),(1,2),(1,10),(2,3),(3,4),(4,5),(5,6),(6,7),(6,32),(7,8),(7,9),(8,9),(8,14),(9,10),(9,12),(10,11),(11,12),(12,13),(13,14),(14,15),(15,16),(16,17),(17,18),(18,19),(19,20),(20,21),(21,22),(22,23),(23,24),(24,25),(25,26),(26,27),(27,28),(28,29),(29,30),(30,31),(31,32),(32,33),(33,34),(34,35),(35,36),(36,37),(37,38),(38,39),(39,40)]
def upperGraph : SimpleGraph V where
  Adj u v := (min u.val v.val, max u.val v.val) ∈ upperEdges
  symm := ⟨by intro u v h; simpa only [Nat.min_comm, Nat.max_comm] using h⟩
  loopless := ⟨by
    intro v
    have hh : ∀ i : V, ¬ (i.val, i.val) ∈ upperEdges := by decide +kernel
    simpa only [Nat.min_self, Nat.max_self] using hh v⟩
instance : DecidableRel upperGraph.Adj := fun u v =>
  inferInstanceAs (Decidable ((min u.val v.val, max u.val v.val) ∈ upperEdges))
theorem upper_edge_count : upperGraph.edgeFinset.card = 47 := by decide +kernel
def w3 : upperGraph.Walk 7 7 := (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))
theorem w3_isCycle : w3.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w4 : upperGraph.Walk 9 9 := (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))
theorem w4_isCycle : w4.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w5 : upperGraph.Walk 8 8 := (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))
theorem w5_isCycle : w5.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w6 : upperGraph.Walk 7 7 := (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))
theorem w6_isCycle : w6.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w7 : upperGraph.Walk 8 8 := (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))
theorem w7_isCycle : w7.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w8 : upperGraph.Walk 7 7 := (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))
theorem w8_isCycle : w8.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w9 : upperGraph.Walk 1 1 := (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))
theorem w9_isCycle : w9.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w10 : upperGraph.Walk 1 1 := (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))
theorem w10_isCycle : w10.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w11 : upperGraph.Walk 1 1 := (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))
theorem w11_isCycle : w11.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w12 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))
theorem w12_isCycle : w12.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w13 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))
theorem w13_isCycle : w13.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w14 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))
theorem w14_isCycle : w14.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w15 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))
theorem w15_isCycle : w15.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w16 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))
theorem w16_isCycle : w16.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w17 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))
theorem w17_isCycle : w17.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w18 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))
theorem w18_isCycle : w18.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w19 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))
theorem w19_isCycle : w19.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w20 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))
theorem w20_isCycle : w20.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w21 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))
theorem w21_isCycle : w21.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w22 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))
theorem w22_isCycle : w22.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w23 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))
theorem w23_isCycle : w23.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w24 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))
theorem w24_isCycle : w24.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w25 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))
theorem w25_isCycle : w25.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w26 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))
theorem w26_isCycle : w26.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w27 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))
theorem w27_isCycle : w27.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w28 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))))
theorem w28_isCycle : w28.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w29 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))))
theorem w29_isCycle : w29.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w30 : upperGraph.Walk 1 1 := (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))))))
theorem w30_isCycle : w30.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w31 : upperGraph.Walk 1 1 := (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))))))
theorem w31_isCycle : w31.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w32 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))))))))
theorem w32_isCycle : w32.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w33 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))))))))
theorem w33_isCycle : w33.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w34 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))))))))))
theorem w34_isCycle : w34.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w35 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))))))))))
theorem w35_isCycle : w35.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w36 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))))))))))))
theorem w36_isCycle : w36.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w37 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))))))))))))
theorem w37_isCycle : w37.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w38 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))))))))))))))
theorem w38_isCycle : w38.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w39 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))))))))))))))
theorem w39_isCycle : w39.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w40 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil))))))))))))))))))))))))))))))))))))))))
theorem w40_isCycle : w40.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
def w41 : upperGraph.Walk 0 0 := (SimpleGraph.Walk.cons (v := (1 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (2 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (3 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (4 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (5 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (6 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (7 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (8 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (9 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (10 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (11 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (12 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (13 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (14 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (15 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (16 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (17 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (18 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (19 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (20 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (21 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (22 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (23 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (24 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (25 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (26 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (27 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (28 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (29 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (30 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (31 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (32 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (33 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (34 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (35 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (36 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (37 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (38 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (39 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (40 : V)) (by decide +kernel) (SimpleGraph.Walk.cons (v := (0 : V)) (by decide +kernel) SimpleGraph.Walk.nil)))))))))))))))))))))))))))))))))))))))))
theorem w41_isCycle : w41.IsCycle := by
  apply SimpleGraph.Walk.isCycle_iff_isPath_tail_and_le_length.mpr
  exact ⟨SimpleGraph.Walk.IsPath.mk' (by decide +kernel), by decide +kernel⟩
theorem upper_pancyclic : Pancyclic upperGraph := by
  intro l hlo hhi
  have cases : l = 3 ∨ l = 4 ∨ l = 5 ∨ l = 6 ∨ l = 7 ∨ l = 8 ∨ l = 9 ∨ l = 10 ∨ l = 11 ∨ l = 12 ∨ l = 13 ∨ l = 14 ∨ l = 15 ∨ l = 16 ∨ l = 17 ∨ l = 18 ∨ l = 19 ∨ l = 20 ∨ l = 21 ∨ l = 22 ∨ l = 23 ∨ l = 24 ∨ l = 25 ∨ l = 26 ∨ l = 27 ∨ l = 28 ∨ l = 29 ∨ l = 30 ∨ l = 31 ∨ l = 32 ∨ l = 33 ∨ l = 34 ∨ l = 35 ∨ l = 36 ∨ l = 37 ∨ l = 38 ∨ l = 39 ∨ l = 40 ∨ l = 41 := by omega
  rcases cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact ⟨7, w3, w3_isCycle, by decide +kernel⟩
  · exact ⟨9, w4, w4_isCycle, by decide +kernel⟩
  · exact ⟨8, w5, w5_isCycle, by decide +kernel⟩
  · exact ⟨7, w6, w6_isCycle, by decide +kernel⟩
  · exact ⟨8, w7, w7_isCycle, by decide +kernel⟩
  · exact ⟨7, w8, w8_isCycle, by decide +kernel⟩
  · exact ⟨1, w9, w9_isCycle, by decide +kernel⟩
  · exact ⟨1, w10, w10_isCycle, by decide +kernel⟩
  · exact ⟨1, w11, w11_isCycle, by decide +kernel⟩
  · exact ⟨0, w12, w12_isCycle, by decide +kernel⟩
  · exact ⟨0, w13, w13_isCycle, by decide +kernel⟩
  · exact ⟨0, w14, w14_isCycle, by decide +kernel⟩
  · exact ⟨0, w15, w15_isCycle, by decide +kernel⟩
  · exact ⟨0, w16, w16_isCycle, by decide +kernel⟩
  · exact ⟨0, w17, w17_isCycle, by decide +kernel⟩
  · exact ⟨0, w18, w18_isCycle, by decide +kernel⟩
  · exact ⟨0, w19, w19_isCycle, by decide +kernel⟩
  · exact ⟨0, w20, w20_isCycle, by decide +kernel⟩
  · exact ⟨0, w21, w21_isCycle, by decide +kernel⟩
  · exact ⟨0, w22, w22_isCycle, by decide +kernel⟩
  · exact ⟨0, w23, w23_isCycle, by decide +kernel⟩
  · exact ⟨0, w24, w24_isCycle, by decide +kernel⟩
  · exact ⟨0, w25, w25_isCycle, by decide +kernel⟩
  · exact ⟨0, w26, w26_isCycle, by decide +kernel⟩
  · exact ⟨0, w27, w27_isCycle, by decide +kernel⟩
  · exact ⟨0, w28, w28_isCycle, by decide +kernel⟩
  · exact ⟨0, w29, w29_isCycle, by decide +kernel⟩
  · exact ⟨1, w30, w30_isCycle, by decide +kernel⟩
  · exact ⟨1, w31, w31_isCycle, by decide +kernel⟩
  · exact ⟨0, w32, w32_isCycle, by decide +kernel⟩
  · exact ⟨0, w33, w33_isCycle, by decide +kernel⟩
  · exact ⟨0, w34, w34_isCycle, by decide +kernel⟩
  · exact ⟨0, w35, w35_isCycle, by decide +kernel⟩
  · exact ⟨0, w36, w36_isCycle, by decide +kernel⟩
  · exact ⟨0, w37, w37_isCycle, by decide +kernel⟩
  · exact ⟨0, w38, w38_isCycle, by decide +kernel⟩
  · exact ⟨0, w39, w39_isCycle, by decide +kernel⟩
  · exact ⟨0, w40, w40_isCycle, by decide +kernel⟩
  · exact ⟨0, w41, w41_isCycle, by decide +kernel⟩
theorem exists_pancyclic_41_47 :
    ∃ G : SimpleGraph V, Nat.card G.edgeSet = 47 ∧ Pancyclic G := by
  refine ⟨upperGraph, ?_, upper_pancyclic⟩
  simpa [Nat.card_eq_fintype_card, SimpleGraph.edgeFinset] using upper_edge_count
end JSP846Standard
#print axioms JSP846Standard.upper_edge_count
#print axioms JSP846Standard.upper_pancyclic
#print axioms JSP846Standard.exists_pancyclic_41_47
run_cmd do
  let axs ← Lean.collectAxioms `JSP846Standard.exists_pancyclic_41_47
  for ax in axs do
    unless #[`propext, `Classical.choice, `Quot.sound].contains ax do
      throwError "Disallowed axiom: {ax}"
